apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks007-0bd0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks007-0bd0"
  template:
    metadata:
      labels:
        app: "myaks007-0bd0"
    spec:
      containers:
        - name: "myaks007-0bd0"
          image: "sampconregistry001.azurecr.io/myaks007"
          ports:
          - containerPort: 5000